'use client'

import { Modal } from '../ui/Modal'
import { Button } from '../ui/Button'
import { Download, Printer, Mail, Calendar, User, FileText } from 'lucide-react'

interface ViewReportModalProps {
  isOpen: boolean
  onClose: () => void
  reportData: {
    title: string
    type: string
    generatedBy: string
    date: string
    period: string
    data: any
    summary: {
      totalPatients: number
      totalVisits: number
      totalRevenue: number
      averageVisitDuration: string
    }
  }
}

export function ViewReportModal({ isOpen, onClose, reportData }: ViewReportModalProps) {
  const handlePrint = () => {
    window.print()
  }

  const handleDownload = () => {
    // Implement download logic
    console.log('Downloading report...')
  }

  const handleEmail = () => {
    // Implement email logic
    console.log('Emailing report...')
  }

  return (
    <Modal
      isOpen={isOpen}
      onClose={onClose}
      title="View Report"
      size="xl"
    >
      <div className="space-y-6">
        {/* Report Header */}
        <div className="bg-gradient-to-r from-indigo-50 to-purple-100 rounded-xl p-6">
          <div className="flex items-center justify-between">
            <div>
              <h2 className="text-2xl font-bold text-gray-900 mb-2">{reportData.title}</h2>
              <div className="flex items-center space-x-6 text-sm text-gray-600">
                <div className="flex items-center space-x-2">
                  <FileText className="w-4 h-4" />
                  <span>{reportData.type} Report</span>
                </div>
                <div className="flex items-center space-x-2">
                  <User className="w-4 h-4" />
                  <span>Generated by: {reportData.generatedBy}</span>
                </div>
                <div className="flex items-center space-x-2">
                  <Calendar className="w-4 h-4" />
                  <span>Period: {reportData.period}</span>
                </div>
              </div>
            </div>
            <div className="text-right">
              <p className="text-sm text-gray-600">Generated on</p>
              <p className="font-semibold text-gray-900">{reportData.date}</p>
            </div>
          </div>
        </div>

        {/* Summary Cards */}
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          <div className="bg-white border border-gray-200 rounded-lg p-4 text-center">
            <div className="text-2xl font-bold text-blue-600 mb-1">
              {reportData.summary.totalPatients}
            </div>
            <div className="text-sm text-gray-600">Total Patients</div>
          </div>
          <div className="bg-white border border-gray-200 rounded-lg p-4 text-center">
            <div className="text-2xl font-bold text-green-600 mb-1">
              {reportData.summary.totalVisits}
            </div>
            <div className="text-sm text-gray-600">Total Visits</div>
          </div>
          <div className="bg-white border border-gray-200 rounded-lg p-4 text-center">
            <div className="text-2xl font-bold text-purple-600 mb-1">
              ${reportData.summary.totalRevenue.toLocaleString()}
            </div>
            <div className="text-sm text-gray-600">Total Revenue</div>
          </div>
          <div className="bg-white border border-gray-200 rounded-lg p-4 text-center">
            <div className="text-2xl font-bold text-orange-600 mb-1">
              {reportData.summary.averageVisitDuration}
            </div>
            <div className="text-sm text-gray-600">Avg. Visit Duration</div>
          </div>
        </div>

        {/* Report Data */}
        <div className="bg-white border border-gray-200 rounded-lg overflow-hidden">
          <div className="bg-gray-50 px-6 py-4 border-b border-gray-200">
            <h3 className="font-semibold text-gray-900">Detailed Breakdown</h3>
          </div>
          <div className="p-6">
            {/* This would contain the actual report data visualization */}
            <div className="text-center py-12">
              <FileText className="w-16 h-16 text-gray-300 mx-auto mb-4" />
              <h4 className="text-lg font-medium text-gray-900 mb-2">Report Data Visualization</h4>
              <p className="text-gray-600">
                Detailed charts and tables would be displayed here based on the report type.
              </p>
            </div>
            
            {/* Sample data table */}
            <div className="mt-6">
              <table className="w-full text-sm text-left">
                <thead className="bg-gray-50">
                  <tr>
                    <th className="px-4 py-2 font-medium text-gray-700">Category</th>
                    <th className="px-4 py-2 font-medium text-gray-700">Count</th>
                    <th className="px-4 py-2 font-medium text-gray-700">Percentage</th>
                    <th className="px-4 py-2 font-medium text-gray-700">Trend</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-gray-200">
                  <tr>
                    <td className="px-4 py-3">General Medicine</td>
                    <td className="px-4 py-3">245</td>
                    <td className="px-4 py-3">35%</td>
                    <td className="px-4 py-3 text-green-600">↑ 12%</td>
                  </tr>
                  <tr>
                    <td className="px-4 py-3">Pediatrics</td>
                    <td className="px-4 py-3">180</td>
                    <td className="px-4 py-3">25%</td>
                    <td className="px-4 py-3 text-green-600">↑ 8%</td>
                  </tr>
                  <tr>
                    <td className="px-4 py-3">Surgery</td>
                    <td className="px-4 py-3">120</td>
                    <td className="px-4 py-3">17%</td>
                    <td className="px-4 py-3 text-red-600">↓ 5%</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>

        {/* Action Buttons */}
        <div className="flex justify-between items-center pt-6 border-t border-gray-200">
          <div className="text-sm text-gray-600">
            Report ID: {Math.random().toString(36).substr(2, 9).toUpperCase()}
          </div>
          <div className="flex space-x-3">
            <Button variant="secondary" size="sm" onClick={handlePrint}>
              <Printer className="w-4 h-4 mr-2" />
              Print
            </Button>
            <Button variant="secondary" size="sm" onClick={handleDownload}>
              <Download className="w-4 h-4 mr-2" />
              Download PDF
            </Button>
            <Button variant="secondary" size="sm" onClick={handleEmail}>
              <Mail className="w-4 h-4 mr-2" />
              Email Report
            </Button>
          </div>
        </div>

        {/* Footer */}
        <div className="text-center text-sm text-gray-500">
          <p>This report contains confidential information. Please handle with care.</p>
          <p className="mt-1">Generated by Hospital HMS • {new Date().toLocaleDateString()}</p>
        </div>
      </div>
    </Modal>
  )
}